version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      - spring_datasource_url=jdbc:mysql://db:3306/ensolvers
      - spring_datasource_username=admin
      - spring_datasource_password=admin
    ports:
      - 8080:8080

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - 80:80

  db:
    image: 'mysql:8.0.28-debian'
    container_name: db
    environment:
      - MYSQL_DATABASE=ensolvers
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306
